name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - '*.x'

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install composer dependencies
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
